name: Deploy to App Engine

on:
  push:
    branches: [ test-actions ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          working_directory: directory/
          deliverables: api.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: true
          version: v1
