name: Deploy to App Engine

on:
  push:
    branches: [ test-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          working_directory: dashboard/
          deliverables: api.yaml app.yaml dispatch.yaml index.yaml upload.yaml upload-processing.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: true
          version: v1
